//go:build windows
package main
import("encoding/json";"fmt";"io";"net/http";"os";"os/exec";"path/filepath";"strconv";"strings";"sync";"syscall";"time";"unsafe")
const version="1.0.0"; const port=51339; const appURL="https://yoandarz.github.io/chronix/?alert=1"
type Day struct{Enabled bool `json:"enabled"`; Time string `json:"time"`}; type Settings struct{Range int `json:"global_range_days"`; Snooze int `json:"snooze_minutes"`; Sound bool `json:"sound_enabled"`; Enabled bool `json:"auto_alert_enabled"`; Schedule map[string]Day `json:"alert_schedule"`}; type State struct{Version int `json:"version"`; UpdatedAt string `json:"updatedAt"`; Settings Settings `json:"settings"`; Records []json.RawMessage `json:"records"`}
var mu sync.Mutex; var current State; var lastMinute=""; var snoozedUntil time.Time
func dataPath()string{d:=os.Getenv("LOCALAPPDATA");if d==""{d=os.TempDir()};d=filepath.Join(d,"Chronix");_ = os.MkdirAll(d,0755);return filepath.Join(d,"bridge_state.json")}
func saveState(b []byte){_ = os.WriteFile(dataPath(),b,0600)}
func loadState(){b,e:=os.ReadFile(dataPath());if e==nil{mu.Lock();_ = json.Unmarshal(b,&current);mu.Unlock()}}
func registerStartup(){exe,e:=os.Executable();if e!=nil{return};cmd:=exec.Command("reg.exe","add",`HKCU\Software\Microsoft\Windows\CurrentVersion\Run`,"/v","ChronixAlarmBridge","/t","REG_SZ","/d",`"`+exe+`"`,"/f");cmd.SysProcAttr=&syscall.SysProcAttr{HideWindow:true};_ = cmd.Run()}
func cors(w http.ResponseWriter,r *http.Request){o:=r.Header.Get("Origin");if o=="https://yoandarz.github.io"||strings.HasPrefix(o,"http://localhost")||strings.HasPrefix(o,"http://127.0.0.1"){w.Header().Set("Access-Control-Allow-Origin",o);w.Header().Set("Vary","Origin")};w.Header().Set("Access-Control-Allow-Headers","Content-Type");w.Header().Set("Access-Control-Allow-Methods","GET,POST,OPTIONS")}
func main(){registerStartup();loadState();go ticker();mux:=http.NewServeMux();mux.HandleFunc("/health",func(w http.ResponseWriter,r *http.Request){cors(w,r);if r.Method=="OPTIONS"{return};w.Header().Set("Content-Type","application/json");fmt.Fprintf(w,`{"ok":true,"name":"Chronix Alarm Bridge","version":"%s","mode":"resident"}`,version)});mux.HandleFunc("/state",func(w http.ResponseWriter,r *http.Request){cors(w,r);if r.Method=="OPTIONS"{return};if r.Method!="POST"{http.Error(w,"method",405);return};b,_:=io.ReadAll(io.LimitReader(r.Body,5<<20));var s State;if json.Unmarshal(b,&s)!=nil{http.Error(w,"json",400);return};mu.Lock();current=s;mu.Unlock();saveState(b);w.Header().Set("Content-Type","application/json");io.WriteString(w,`{"ok":true}`)});mux.HandleFunc("/test",func(w http.ResponseWriter,r *http.Request){cors(w,r);if r.Method=="OPTIONS"{return};go func(){time.Sleep(time.Minute);showAlert("Prueba de alarma de Chronix") }();io.WriteString(w,`{"ok":true}`)});mux.HandleFunc("/snooze",func(w http.ResponseWriter,r *http.Request){cors(w,r);if r.Method=="OPTIONS"{return};m,_:=strconv.Atoi(r.URL.Query().Get("minutes"));if m<1{m=10};mu.Lock();snoozedUntil=time.Now().Add(time.Duration(m)*time.Minute);mu.Unlock();io.WriteString(w,`{"ok":true}`)});srv:=&http.Server{Addr:fmt.Sprintf("127.0.0.1:%d",port),Handler:mux};_ = srv.ListenAndServe()}
func ticker(){t:=time.NewTicker(15*time.Second);defer t.Stop();for n:=range t.C{mu.Lock();s:=current.Settings;su:=snoozedUntil;lm:=lastMinute;mu.Unlock();if !su.IsZero()&&n.After(su){mu.Lock();snoozedUntil=time.Time{};lastMinute=n.Format("2006-01-02 15:04")+" snooze";mu.Unlock();go showAlert("Alerta pospuesta de Chronix");continue};if !s.Enabled{continue};key:=strings.ToLower(n.Weekday().String());day,ok:=s.Schedule[key];if !ok||!day.Enabled{continue};minute:=n.Format("2006-01-02 15:04");if day.Time==n.Format("15:04")&&lm!=minute{mu.Lock();lastMinute=minute;mu.Unlock();go showAlert("Chronix · Alerta diaria")}}}
var user32=syscall.NewLazyDLL("user32.dll");var shell32=syscall.NewLazyDLL("shell32.dll");var msgBox=user32.NewProc("MessageBoxW");var shellExec=shell32.NewProc("ShellExecuteW")
func wstr(s string)*uint16{p,_:=syscall.UTF16PtrFromString(s);return p}
func showAlert(title string){mu.Lock();s:=current.Settings;mu.Unlock();mins:=s.Snooze;if mins<1{mins=10};text:=fmt.Sprintf("Revisa tus cumpleaños, eventos y recordatorios próximos.\n\nSí = abrir Chronix\nNo = posponer %d min\nCancelar = cerrar",mins);flags:=uintptr(0x00000003|0x00040000);if s.Sound{flags|=0x00000040};ret,_,_:=msgBox.Call(0,uintptr(unsafe.Pointer(wstr(text))),uintptr(unsafe.Pointer(wstr(title))),flags);if ret==6{shellExec.Call(0,uintptr(unsafe.Pointer(wstr("open"))),uintptr(unsafe.Pointer(wstr(appURL))),0,0,1)}else if ret==7{mu.Lock();snoozedUntil=time.Now().Add(time.Duration(mins)*time.Minute);mu.Unlock()}}
