package com.chronix.app;
import android.app.*;import android.content.*;import android.os.Build;import org.json.*;import java.util.*;
public final class AlarmScheduler {
  static final String PREF="chronix_native", KEY="state"; static final String[] DAYS={"sunday","monday","tuesday","wednesday","thursday","friday","saturday"};
  static void saveAndSchedule(Context c,String json) throws Exception{c.getSharedPreferences(PREF,0).edit().putString(KEY,json).apply();scheduleAll(c,json);}
  static void restore(Context c){String j=c.getSharedPreferences(PREF,0).getString(KEY,"");if(!j.isEmpty())try{scheduleAll(c,j);}catch(Exception ignored){}}
  static void scheduleAll(Context c,String json)throws Exception{JSONObject root=new JSONObject(json),settings=root.optJSONObject("settings");if(settings==null)return;boolean global=settings.optBoolean("auto_alert_enabled",true);JSONObject sched=settings.optJSONObject("alert_schedule");for(int i=0;i<7;i++){int code=4100+i;cancel(c,code);if(!global||sched==null)continue;String key=DAYS[i], hm="09:00";JSONObject d=sched.optJSONObject(key);if(d==null||!d.optBoolean("enabled",true))continue;hm=d.optString("time","09:00");scheduleWeekly(c,code,i+1,hm);}}
  static void scheduleWeekly(Context c,int code,int calDay,String hm){String[] p=hm.split(":");int h=Integer.parseInt(p[0]),m=Integer.parseInt(p[1]);Calendar x=Calendar.getInstance();x.set(Calendar.SECOND,0);x.set(Calendar.MILLISECOND,0);x.set(Calendar.HOUR_OF_DAY,h);x.set(Calendar.MINUTE,m);int delta=(calDay-x.get(Calendar.DAY_OF_WEEK)+7)%7;if(delta==0&&x.getTimeInMillis()<=System.currentTimeMillis())delta=7;x.add(Calendar.DAY_OF_YEAR,delta);Intent in=new Intent(c,AlarmReceiver.class).putExtra("weekly",true).putExtra("code",code);PendingIntent pi=PendingIntent.getBroadcast(c,code,in,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);AlarmManager am=(AlarmManager)c.getSystemService(Context.ALARM_SERVICE);setExact(am,x.getTimeInMillis(),pi);}
  static void scheduleOne(Context c,int code,long when){Intent in=new Intent(c,AlarmReceiver.class).putExtra("weekly",false).putExtra("code",code);PendingIntent pi=PendingIntent.getBroadcast(c,code,in,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);setExact((AlarmManager)c.getSystemService(Context.ALARM_SERVICE),when,pi);}
  static void test60(Context c){scheduleOne(c,4999,System.currentTimeMillis()+60000);}
  static void snooze(Context c,int min){scheduleOne(c,4998,System.currentTimeMillis()+Math.max(1,min)*60000L);}
  static void setExact(AlarmManager am,long at,PendingIntent pi){if(Build.VERSION.SDK_INT>=31&&am.canScheduleExactAlarms())am.setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,at,pi);else if(Build.VERSION.SDK_INT<31)am.setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,at,pi);else am.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,at,pi);}
  static void cancel(Context c,int code){PendingIntent pi=PendingIntent.getBroadcast(c,code,new Intent(c,AlarmReceiver.class),PendingIntent.FLAG_NO_CREATE|PendingIntent.FLAG_IMMUTABLE);if(pi!=null)((AlarmManager)c.getSystemService(Context.ALARM_SERVICE)).cancel(pi);}
}
